Portfolio set up (Mobile first navbar and headline section)
Bettenoch/Portfolio-Setup-Mobile-First pull request #1
Opened 2023-06-07 12:26 UTC by Bettenoch

Made the following changes:
Added navbar section with logo and harmburger menu. Added Headline section.
Added  linters with lighthouse, Weblint and stylint properties.

2023-06-07 13:03 UTC, V-Blaze requested changes
## Hi @Bettenoch  , 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![giphy](https://user-images.githubusercontent.com/107632780/229314554-3700de13-2c00-46d5-bc77-46ad09af7467.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Well-structured code✔
-  Descriptive pull request summary👋 
-  descriptive pull request title✔

 ## Required Changes ♻️
- [ ] I'll suggest you remove these two placeholder comments from your readme file, there were added there to guide you and were meant to be removed while customizing your readme
- - Screenshot:
![Screenshot from 2023-06-07 13-59-40](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/107632780/87aa74e4-7aec-4a5f-81c4-a18e32a11cf9)

- - ![Screenshot from 2023-06-07 14-00-01](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/107632780/e9c208cd-a886-4cac-9c9b-0731902a8538)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 13:03 UTC, V-Blaze commented on index.html
> +    </header>
- [ ] You did a great job using the `header and nav` semantic tag here. :+1: :100: but looking at the screenshot below, you can see that this section has some styling issues,
- [ ] The logo and the hamburger menu icon images are not displaying, I think this is due to the `src` URL. The first folder should be `assets` as you named it and not `Assets`, these file names are case sensitive. I'll suggest you update this accordingly. :smile: :small_airplane: 

- - Screenshot:
![Screenshot from 2023-06-07 13-50-41](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/107632780/0daea662-5261-4199-bbd8-f0db7d602b5b)

2023-06-07 13:03 UTC, V-Blaze commented on index.html
> +
- [ ] You did great using a section semantic tag here also, :+1: :+1: 
- [ ] Just like I pointed out above, you can see that your images are not displaying properly, I'll suggest you update their src URL. :+1: 
- [ ] The According to the Figma design, the background color is not white, I'll suggest you update this accordingly. :+1: 
- [ ] As you can see from the video below, the paragraph text is not visible, I think you need to check the styling for this section and make sure you are using style rules supported by all browsers.

- - YOUR PROJECT VIDEO:- 

https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/107632780/45d43120-d0ed-44d9-80a3-6ea34bc03b38

_For reference this project was opened in Chrome browser_

- [ ] FIGMA DESIGN:
![Screenshot from 2023-06-07 13-55-55](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/107632780/b62dab34-3508-44ea-9af8-f0ecc9c5fd2b)

2023-06-08 05:13 UTC, Bettenoch commented
@V-Blaze Thank You for reviewing mg code. I have made the changes as requested how should I Proceed?

2023-06-08 08:27 UTC, Ibizugbe requested changes
Hi @Bettenoch 👋👋👋, 

![tryagain](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/64643995/2dbfc5ea-3f79-4078-bb54-b91c7a89e941)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are passing👍.
- [x] Broken links to images have been fixed as requested by the previous reviewer👍.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 08:27 UTC, Ibizugbe commented on index.html
> +        </nav>
Nice job fixing the broken links as requested by the previous reviewer👍. Currently, your toolbar has a lot of spacings (top and bottom) making it look a bit different from the given design😉. I think you can make the image logo smaller so as to retain the height of the toolbar as shown in the design😉.

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img width="350" alt="image" src="https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/64643995/2a58c5e1-1810-473a-9cc3-a97724b679d1">|<img width="350" alt="image" src="https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/64643995/4a59f86d-b68d-4aaf-8088-293026b1059b">|

2023-06-08 08:27 UTC, Ibizugbe commented on index.html
> +                    <img class="background-image" src="/Assets/images/Illustration.svg" alt="header-banner">
I suggest you work on the position of the background image so as to match the given design😉. currently, as a result of the current position of the background image, some of the texts are hard to see which can lead to a frustrating user experience😉. kindly ensure your background image is rightly positioned as shown in the design😉. try to consider the spacings around the image in the design👍.

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img width="350" alt="image" src="https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/64643995/c928d87e-14d1-429c-bacf-a0e262cf85f3">|<img width="350" alt="image" src="https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/64643995/17c476ed-ee88-4221-89e3-9c55125b39b9">|

2023-06-10 10:52 UTC, Bettenoch commented
Hello @V-Blaze I have made changes to my project  but I constantly getting this Weblint error regarding my node. Someone has advised that I remove the Weblint section on linters.yml file from line 24 to 29 but I know that we should confirm from our code reviewers. Please advise on how I should proceed.
![node error](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/99537435/9f8c12d6-97c4-4d2c-bd31-c0420d322249)

2023-06-10 11:02 UTC, Bettenoch commented
Hello @Ibizugbe  I have made changes to my project but I am constantly getting this Weblint error regarding my node. Someone has advised that I remove the Weblint section on linters.yml file from line 24 to 29 but I know that we should confirm from our code reviewers. Please advise on how I should proceed.
![node error](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/99537435/dc2a2638-5c47-4478-86d7-4b589cc93778)

2023-06-10 11:11 UTC, Ibizugbe commented
Hello @Bettenoch 👋👋, There's an allowance for this error today😉. You can proceed to submit, and your project should be reviewed without any considerations to the error👍. 

But on your own, I suggest you try reinstalling linters on the project. take all the linter files from your local computer and from github (the branch with this PR and the main branch). after that, download the latest linters from the repo and setup everything afresh😉. I think this might work😉.

2023-06-10 11:16 UTC, Bettenoch commented
> 

Okay Thank You @Ibizugbe  I will consider reinstalling Linter files once again.

2023-06-10 11:22 UTC, Ibizugbe commented
Hello @Bettenoch , I didn't suggest you submit a project without webhint. There's an allowance for that webhint error and a reviewer can only proceed to review your project if that error is seen. I suggest you kindly add the webhint file and only submit if that error persists👍.

2023-06-10 11:37 UTC, IngDavidTM approved these changes
Hi @Bettenoch 🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

- [OPTIONAL] You did an outstanding job implementing the necessary changes :+1:. However, I've noticed that in your HTML and CSS files, the folder for assets is referred to as "Assets" instead of "assets." This inconsistency is causing issues with the images. I kindly request you to correct it :+1:.

This is how it looks on my device (I noticed that you have the same issue in the previous request that's why I request it as Optional, but it is important to change the directory:

![Screenshot from 2023-06-10 06-27-42](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/105117832/8533b54a-f9ab-481b-a529-6958fb049790)



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 13:21 UTC, merged