Mobile menu section
Bettenoch/Portfolio-Setup-Mobile-First pull request #7
Opened 2023-06-27 11:43 UTC by Bettenoch

In this section I made the following changes:
    ♻Added popup.js 
    ♻Added onClick functionality on the hamburger menu for mobile version
    ♻Added onClick functionality on the navlist items for more user experience.
    ♻Restyled mobile menu section

Thank You for reviewing my portfolio!! 🙏

2023-06-27 13:38 UTC, Reem-lab reviewed
# Hi @Bettenoch, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌❌❌

You have submitted a project, that should be pair programming but you made it solo so please reach out to your partner to collaborate with you in the milestone and if you can't reach out send a message to the student sucess that your partner don't respond to your messges and if you are allowed to make it solor put a screentshot to the mail from student scuess ✅🔥✨

![image](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/58553711/503fd007-b350-4213-884a-03ff6a5a7655)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-27 14:53 UTC, Gambit142 reviewed
Hi @Bettenoch 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- This is a pair-programming activity and you ought to collaborate with your partner. Kindly collaborate with your partner as mentioned by the first reviewer. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-27 17:03 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-27 17:03 UTC, Qoosim commented on style.css
>    box-shadow: 0 1.2rem 3.2rem rgba(0, 0, 0, 0.03);
- [ ] It is required to stick to the Figma design as much as possible. Your overlay background is supposed to cover the whole height of the page, but this is not so on your design. Kindly ensure the overlay fills the whole page as your mobile menu items appears when the hamburger icon is clicked.

### Your Design
![your-desing](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/26597432/e4e55b9a-4b36-4f4a-8d6e-dac47039b5d9)

### Figma Design
![figma-design](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/26597432/ae258408-cfe4-45c5-b1f0-7b05bb1fd3cf)

- [ ] Kindly reduce the margin left for all the menu items so as to match the Figma design

### Your Design
![your-space](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/26597432/85e60fb0-d214-4928-95cd-47435c887c09)

### Figma Design
![figma-space](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/26597432/bcd477ea-2bea-40b6-b363-b619428b00dc)

2023-06-28 06:09 UTC, Efiamotu-1 approved these changes
Hi @Bettenoch , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR Title & summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 06:09 UTC, Efiamotu-1 commented on index.html
[OPTIONAL]
- [ ] From the figma image below you can see that the portfolio comes first before the about, but in your design you have plaved the about before the portfolio, this is inconsistent with the provided figma design please make sure to make this change it is important your design matches the figma template as much as possible. :+1: 
- [ ] I also noticed that once i click on either the `portfolio, about or contact` and i try to click the menu again it won't open until i do it a second time. this is majorly coming from your javascript implementation please try to fix these optional requiremnts befoe merging your branch. Thank you :+1: :sparkles: 
- figma design
![p-1](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/89055502/1ec2658a-4d3b-4c0c-a549-0681bfdbfa1f)
- your design
![y-1](https://github.com/Bettenoch/Portfolio-Setup-Mobile-First/assets/89055502/ab0259e8-7658-44cd-99f2-1a17def9e034)

2023-06-28 07:53 UTC, merged